---
title: "E-Commerce - Creating Customer Clusters"
output: html_document
---
<style> 
pre { 
  text-align: left;
  border: 1px solid #ccc; 
  padding: 8px; 
  margin-bottom: 20px; 
  background: #fafafa; 
  white-space: pre; 
  } 
  </style>

# Context

This dataset contains 1,000,000 rows that simulates e-commerce shopping patterns. This data was sourced from Kaggle and uses the following tools: Pandas, Matplotlib, Sickit-learn, KMeans

# Approach

My aim is to create customer clusters using KMeans in order to effectively target advertising to the correct demographics to maximise returns. This will be based on variables like age, education level, product views, product types and ad clicks.

## Data Importing

I started by importing and exploring the data, checking for completeness and standardisation. I created a function to check for the completeness of a few demographic variables to understand what the data looks like - it looks like we have standardisation in the columns with even spread of values and no anomalous results.

```{r, knitr, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = "")
```

```{python, data import, results = FALSE}

import pandas as pd
import sklearn as sklearn
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import seaborn as sns
import matplotlib.pyplot as plt

p2_data_import = pd.read_csv(r"C:\Users\Matthew.Webb12\Desktop\GitHub Repos\Portfolio\python data\e_commerce_shopper_behaviour_and_lifestyle.csv")

# Exploring the data for completeness with a function
# This dataset is large: 57 x 1,00,000

def variable_counts(column):
  counts = p2_data_import[column].value_counts()
  formatted_counts = counts.apply(lambda x: f"{x:,}")
  percentages = p2_data_import[column].value_counts(normalize=True).mul(100).round(1)
  result = pd.concat([formatted_counts, percentages], axis = 1, keys = ['Count', 'Percentage'])
  return result

employment_status_table = variable_counts("employment_status")
education_level_table = variable_counts("education_level")
budget_table = variable_counts("budgeting_style")

```


<div style="display:flex; gap:20px;">

<div style="flex:1;">

```{python, echo = FALSE, comment="", results="markup"}
print(employment_status_table)
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(budget_table)
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(education_level_table)
```
</div>

</div>

<br>

## Creating Clusters

### Column Types

Now I want to start creating my customer clusters, first determining the types of the columns, then encoding the categorical variables so they can be quantified by the clustering.

```{python clustering-test, echo=TRUE, include=TRUE, comment="", results="hide", warnings=FALSE, message=FALSE}

# Dropping the user_id column
p2_data_cleaned = p2_data_import.drop(columns = ["user_id"])

# Separating the columns into numeric and categorical, this is so the KMeans will run correctly
numeric_cols = p2_data_cleaned.select_dtypes(include = ['int64', 'float64']).columns
categorical_cols = p2_data_cleaned.select_dtypes(include=['object', 'category', 'string', 'str']).columns

# Now I need to scale the numeric columns and encode the categorical columns
# This is so KMeans treats the numeric columns equally and can effectively read the categorical columns
column_encoding = ColumnTransformer(
    transformers = [
      ("num", StandardScaler(), numeric_cols),
      ("cat", OneHotEncoder(handle_unknown = "ignore"), categorical_cols)
    ]
)

# Now applying the transformation code to the data
p2_data_transformed = column_encoding.fit_transform(p2_data_cleaned)

# Next I need to determine the most efficient number of clusters using the 'elbow method'
# Creating an empty dictionary to store the values
wcss = []

# Here I've selected the model to test for 2 to 20 clusters and then plot so we can see where the diminishing returns occurs
for k in range(2, 20):
    km = KMeans(n_clusters = k, random_state = 123)
    km.fit(p2_data_transformed)
    wcss.append(km.inertia_)
```

```{python, echo=FALSE, results='hide', warnings=FALSE, message=FALSE}
plt.plot(range(2, 20), wcss, marker='o')
plt.xlabel("Number of clusters /k")
plt.xticks(range(2, 20))
plt.ylabel("WCSS")
plt.title("Cluster Testing via Elbow Method")
plt.show()
```

<br><br><br>

From the above plot 5 clusters is where the gradient starts to become more shallow so I will use 5 clusters in this analysis. So now I need to run a final KMeans clustering.

```{python kmeans, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

# KMeans clustering using 8 clusters
p2_kmeans = KMeans(n_clusters = 5, random_state = 123)
p2_kmeans.fit(p2_data_transformed)
labels = p2_kmeans.labels_

# Adding the new clustering column to my data 
p2_data_cleaned["cluster"] = labels
p2_data_clustering = p2_data_cleaned

# Now I need to add the categorical columns in in order to get a full picture of the cluster profiles
# Pulling the categorical columns from the earlier encoding
cat_cols_initial = column_encoding.named_transformers_["cat"]
cat_cols = cat_cols_initial.get_feature_names_out(categorical_cols)

# Combining with the numeric
all_cols = list(numeric_cols) + list(cat_cols)

p2_data_all_cols = pd.DataFrame(
    p2_data_transformed.toarray() if hasattr(p2_data_transformed, "toarray") else p2_data_transformed,
    columns=all_cols
)

# Creating a dataframe with the full list of columns
p2_data_all_cols["cluster"] = labels
```

```{python cluster plot, echo=FALSE, results='hide', warnings=FALSE, message=FALSE}
# The final step is to pull the greatest variance among clusters and turn this into insights

# First let's visualise our clusters
# This creates a new plot so it doesnt overwrite the previous
plt.figure(figsize=(8,6))  

pca = PCA(n_components=2)
pca_result = pca.fit_transform(p2_data_all_cols.drop(columns=["cluster"]))

# main scatterplot
scatter = plt.scatter(
    pca_result[:,0],
    pca_result[:,1],
    c=labels,
    cmap="tab10",
    s=10
)

# auto-generate legend with correct colours
handles, _ = scatter.legend_elements(prop="colors")
plt.legend(handles, [f"Cluster {i}" for i in sorted(set(labels))], title="Clusters")

plt.title("PCA of Clusters")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

```

## Interpretation

This plot tells me some key things about my clustering, the clustering has been effective due to the cluster 'blobs' being all similar sizes with distinct customer behaviours in each due to there being minimal overlap. No empty spaces tells me the behaviour differences between the clusters aren't radically different but vary gradually from one cluster to the next. 

Before my final summary I need one more step, adding in a means table and pulling the dominant cluster features from each cluster so I can build a profile for the business to target actions to.

```{python dominant cluster features, comments = "", results='markup', include = TRUE}

# In order to now interpret the results of this clustering I need to create a means table, and a dominant variance for each cluster list

# Means table
p2_data_clustering_full = p2_data_all_cols.groupby("cluster").mean()
p2_data_clustering_full = p2_data_clustering_full.round(4)

# Dominant variance
dom_cluster_feature = p2_data_clustering_full.copy()

dom_features_per_cluster = {}

for c in dom_cluster_feature.index:
    top_features = (
        dom_cluster_feature.loc[c]
        .sort_values(ascending=False)
        .head(15)
        *100
    )
    dom_features_per_cluster[c] = top_features.round(2)
    
```

Now I have my cluster profiles I can provide business insights into how to target these clusters effectively, for the sake of space I will only analyse two clusters using some of their most dominant features calculated in the previous step.

### Cluster 1

```{python, conclusions, comments = "", results='markup', include = TRUE}
print(dom_features_per_cluster[0])

```

- **Split evenly among genders** - Use gender neutral ads to maximise engagement
- **Predominantly on mobile devices** - Provide push-notifications and mobile based deals
- **Split evenly among budget types** - This point is important, you should use tiered pricing models on products, i.e. low, medium and high price, this will again maximise engagement by appealing to all budget types. You should also make your medium price much higher than your low price but not that much lower than your high price, this employs psychological mechanism that makes people purchase the medium and high priced items more.
- **Predominantly lives in urban areas** -  Prioritise click-and-collect

### Cluster 2

```{python, conclusions continued, comments = "", results='markup', include = TRUE}
print(dom_features_per_cluster[1])

```
- **Very High cart abandonment rate** - Offer promotional deals like free returns, or pay in installments, and make the buying process quicker with one-click payment to prevent customers backing out. Make sure to also save their carts if customers leave the site, and offer them discounts on the cart if they come back and pay.
- **Very impulsive** - This is a relatively easy behaviour to utilise because it works against the customer, offer them time sensitive deals like flash deals
- **Also predominantly on mobile devices** - So utilise mobile push notifications about the cart abandonment deals and incorporate mobile paying services like apple pay as this will pair with their impulsivity if they don't need to input card details, giving them time to think about their purchase and lose interest
- **High social sharing frequency** - This can be a useful feature as it implies that people with respond to things like referral bonuses and sharing bonuses if they share on social media

