---
title: "Carbon Emissions: How to Optimise Fuel Efficiency Without Comprimising on Deliveries"
output: html_document
header-includes:
  - |
    <style>
      h1 {font-size:15px;}
      h2 {font-size:10px;}
    <style>
---
<style> 
pre { 
  text-align: left;
  border: 1px solid #ccc; 
  padding: 8px; 
  margin-bottom: 20px; 
  background: #fafafa; 
  white-space: pre; 
  } 
  </style>
  
# Context
This fictional delivery company uses a range of vehicles, routes, and delivery types, I will determine how to improve their fuel efficiency without impacting their revenue.

This data was sourced from Kaggle and uses the following tools: Pandas, Matplotlib, Seaborn

# Approach

I will inspect the data and the counts of key variables, then calculate the mean fuel usage for for those key variables. I will then inspect the effects of load utilization on fuel efficiency and test it using regression analysis to identify significant relationships. Finally, I will create a matrix of of averages for all combinations of vehicle and delivery types to calculate how much fuel could be saved by switching vehicle types on certain routes.

## Data Importing

I started by importing and exploring the data, checking for completeness and standardisation.
```{r, knitr, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = "")
```

```{python, data import, results = FALSE}

import pandas as pd
import seaborn as sea
import matplotlib.pyplot as plt
import statsmodels.api as sm

p1_data_import = pd.read_excel(r"C:\Users\Matthew.Webb12\Desktop\GitHub Repos\Portfolio\python data\carbon_emissions_fleet_dataset.xlsx")

# Function for counts of variables
def variable_counts(column):
  counts = p1_data_import[column].value_counts()
  formatted_counts = counts.apply(lambda x: f"{x:,}")
  percentages = p1_data_import[column].value_counts(normalize=True).mul(100).round(1)
  result = pd.concat([formatted_counts, percentages], axis=1, keys=['Count', 'Percentage'])
  return result

vehicle_type_table = variable_counts("Vehicle_Type")
route_type_table = variable_counts("Route_Type")
delivery_type_table = variable_counts("Delivery_Type")

```

Here we have the counts of the variables which has highlighted an anomalous row we will remove in the vehicle type column, aside from that we can see these key columns don't contain any na incidents or non-standard values.

<div style="display:flex; gap:20px;">

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(vehicle_type_table)
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(route_type_table)
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(delivery_type_table)
```
</div>
</div>
<br>
I also want to check the count of delivery types for each vehicle type, and the average distance for each delivery type as these will be key metrics for later.

```{python, vehicle + delivery averages, echo=FALSE, comment="", results="markup"}
count_delivery_type = p1_data_import.groupby("Vehicle_Type")["Delivery_Type"].value_counts()
mean_distance = p1_data_import.groupby("Delivery_Type")["Distance_km"].mean()
```

<div style="display:flex; gap:20px;">

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(mean_distance)
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(count_delivery_type)
```

</div>

</div>

<br>

## Data Handling & Descriptive Analysis

Here I can see the break down of the key columns I will be using for my calculations, my next step is to handle the data and create an average fuel efficiency per vehicle and delivery type, and see how this compares to the averages of the type combinations. These tables will be used at a later stage.

```{python, average fuel efficiency}

# Handling columns
p1_data_import["CO2_Emissions_kg"] = (p1_data_import["CO2_Emissions_g"] / 1000).round(2)
p1_data_import_cleaned = p1_data_import[p1_data_import["Vehicle_Type"] != "S"]

columns_to_check = ["Vehicle_Type", "Route_Type", "Delivery_Type"]
# Creating an average fuel efficiency per litre for each vehicle, delivery and route type
average_tables = {}

for col in columns_to_check:
  average_tables[col] = p1_data_import_cleaned.groupby(col)["Fuel_Efficiency_kmpl"].mean().to_frame(name="Average kmpl")
```

<div style="display:flex; gap:20px;">

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(average_tables[columns_to_check[0]])
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(average_tables[columns_to_check[1]])
```
</div>

<div style="flex:1;">
```{python, echo = FALSE, comment="", results="markup"}
print(average_tables[columns_to_check[2]])
```
</div>

</div>

## Load Utilisation

Before I start comparing the delivery and vehicle types for fuel efficiency I want to check how load utilization effects fuel efficiency, as ultimately maximizing fuel efficiency is what we are aiming to achieve here. We can see that for Electric vehicles and Bikes the fuel efficiency decreases steadily as the load utilization increases, whereas for CNG Trucks and Diesel Vans it increases. My next step is to calculate if these changes are significant.

</div>
</div>

```{python, load utilisation plot}
# Plotting the effects of load utilisation on fuel efficiency
sea_load_util = sea.lmplot(
  data=p1_data_import_cleaned, 
  x="Load_Utilization_%", 
  y="Fuel_Efficiency_kmpl", 
  hue="Vehicle_Type", 
  height=6, 
  aspect=1.3, 
  scatter = False 
  )
plt.xlabel("Load Utilization %")
plt.ylabel("Fuel Efficiency kmpl")
plt.show()
```

## Regression Test

I will now employ a regression analysis to see how much fuel efficiency is impacted by load utilisation across vehicle types as this will tell us where to maximize it and where to not.

```{python, regression, results=FALSE}
# Creating empty dictionary to store results
results = {} 

for vtype in p1_data_import_cleaned["Vehicle_Type"].unique(): 
  # Subsetting data based on vehicle type
  subset = p1_data_import_cleaned[p1_data_import_cleaned["Vehicle_Type"] == vtype] 
  # Adding in predictor variable coefficient
  X = sm.add_constant(subset["Load_Utilization_%"])
  y = subset["Fuel_Efficiency_kmpl"] 
  # Running regression
  model = sm.OLS(y, X).fit() 
  results[vtype] = model
```

I will simplify the results by extracting just the p_values and impact on kmpl for every 10% increase in load.

```{python, regression results}
# Empty dictionary to store results
coef_table = [] 

for vtype, model in results.items(): 
  # Pulling kmpl change for every 1% load increase
  beta_1 = model.params["Load_Utilization_%"] 
  # Pulling p values
  pval = model.pvalues["Load_Utilization_%"] 
  # Creating a better metric of kmpl change for every 10% increase
  beta_10 = beta_1 * 10
  
  coef_table.append({ 
    "Vehicle Type": vtype, 
    "kmpl change per 10% load increase": beta_10, 
    "p_value": pval 
    }) 
    
coef_results = pd.DataFrame(coef_table) 
print(coef_results(index=False))
```
As you can see every p value is >0.05 meaning none of the results are significant, indicating that increasing the load has a negligible effect on fuel efficiency for every vehicle type.

## Mean Testing

I created a function that calculates the averages for each combination of delivery and vehicle types for the other key metrics in the data.

```{python, average function, results='hide'}

# Creating function to compute means
def matrix_function(value_column):
  return p1_data_import_cleaned.pivot_table(
    index="Vehicle_Type",
    columns="Delivery_Type",
    values=value_column,
    aggfunc="mean"
  ).round(2).T

on_time_matrix = matrix_function("On_Time_Delivery")
co2_matrix = matrix_function("CO2_Emissions_kg")
fuel_matrix = matrix_function("Fuel_Efficiency_kmpl")

# Now combining them into one matrix for ease of reading
combined_matrix = pd.concat(
    [on_time_matrix, co2_matrix, fuel_matrix],
    axis=0,
    keys=["On_Time", "CO2_kg", "Fuel_kmpl"]
)

combined_matrix.index = combined_matrix.index.map('_'.join)
```

```{python, echo=FALSE, include=FALSE, results='asis'}

md_table = combined_matrix.to_markdown(index=True)

print(f"""
<div style='text-align:center;'>

{md_table}

</div>
""")
```

Now we can clearly see how the averages of the combinations stack up against the average for the whole variable, this shows us which combinations are preforming below average and could do with reorganising. 

### Conclusion

- **Fuel Efficiency:** - Bikes have the highest fuel efficiency for same day deliveries with 16.07 and electric vans have the lowest with 14.57. Currently bikes are only delivering 15% of same day deliveries so there is scope to shift bikes from express to same day, as express is their lowest performing metric for on time deliveries. Using the below equation you can calculate how much fuel you would save per delivery on average:

$$
Fuel\;saved = (\frac{1}{Vehicle\;1\;Av.\;kmpl}-\frac{1}{Vehicle\;2\;Av.\;kmpl})*Average\;distance
$$ 
So this give you 0.65 litres saved per delivery.
$$
Fuel\;saved = (\frac{1}{14.57}-\frac{1}{16.07})*101
$$ 

- **CO2 kg:** - Same day delivery for diesel vans produces >2kg of fuel per delivery on average, compared to electric vans which has a lower average fuel cost. So moving some of the same day deliveries over from diesel to electric will lower the CO2 emissions without compromising deliveries.

- **Load Utilisation:** - Diesel vans and electric vans both have a steady decline in their fuel efficiency as load utilisation increases, with electric vehicles seeing a bigger drop. However, my coefficient table indicates that these observations are not significant.
