---
title: "Projects"
output: html_document
---

I've conducted end-to-end analysis on many projects at NHS England, from adhoc data requests and recurring reports for internal and 3rd party use, to quarterly publications regarding a wide range of metrics. I will briefly talk about some recent publications here.

# **Project 1** - Patient Safety Event Data Quarterly Publication

My team helped set up the Learn from Patient Safety Events (LFPSE) service is a national NHS system for the recording and analysis of patient safety events that occur in healthcare. The service introduces a range of innovations to support the NHS to improve learning from the over 2.5 million patient safety events recorded each year, to help make care safer. LFPSE is now in use across the NHS, and organisations have switched to recording patient safety events onto the new LFPSE service using LFPSE-compliant local systems, rather than the National Reporting and Learning System (NRLS), which was decommissioned on 30 June 2024. 

[The full report can be found here.](https://www.england.nhs.uk/statistics/statistical-work-areas/patient-safety-data/2025-26/quarter-2-2025-26-july-august-september-2025/)

I was personally in charge of creating a new quarterly report using this data in order to make it public. This allows people to access aspects of the data without having to come to my team first, decreasing the amount of requests we get and increasing the accessibility of the data for public use. 

This project involved many different analytical tools and required me to pull data from multiple sources, clean it, handle missing data and anonymisation issues, and create new metrics and plots to visualise trends. 

# Bed Days 

One of the metrics I created is the bed days formula, some NHS Trusts are bigger than others and offer different types of care and have different facilities; so directly comparing the number of their reports is unfair and unrepresentative. The bed days calculation rectifies this by standardising activity across NHS Trusts, the data was taken from the [KH03 mandatory data collection](https://www.england.nhs.uk/statistics/statistical-work-areas/bed-availability-and-occupancy/bed-data-overnight/) and is also an example of retrieving data from another source and amalgamating it with our LFPSE data:\

$$
Recording\;rate = \frac{Number\;of\;incidents}{Bed\;days\;in\;quarter}*1,000
$$ 



- Project 2
- Project 3